---
version: "3.9"

services:
  audiobookshelf:
    image: advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    hostname: audiobook
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      traefik-int:
    environment:
      - TZ=Europe/Kyiv
    volumes:
      - /volume1/MediaFiles/AudioBooks:/audiobooks:rw
      - ./workdir/podcasts:/podcasts:rw
      - ./workdir/config:/config:rw
      - ./workdir/metadata:/metadata:rw

networks:
  traefik-int:
    external: true
